---
title: "a6"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)  
library(readxl)
library(readr)
library(sf)
library(colorspace)
library(ggplot2)
library(ggpubr)
library(stringr)
```


```{r}
county <- st_read('tl_2019_us_county-1/tl_2019_us_county.shx')
vote <- read_csv('data/countypres_2000-2016.csv') %>% filter(party == 'republican')
vote['proportion'] = vote['candidatevotes']/vote['totalvotes']
vote$FIPS <- as.character(vote$FIPS)
vote$FIPS <- str_pad(vote$FIPS, width = 5, side="left", pad="0")
vote <- vote %>% left_join(county, by = c('FIPS'='GEOID'))

# CA vote 
CA_Vote <- vote %>% filter(state == 'California')
CA_Vote2008 <- ggplot(CA_Vote%>% filter(year==2008), aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +scale_fill_distiller(name="CA Vote Percent Republican Presidental 2008", palette = "Reds")
CA_Vote2012 <- ggplot(CA_Vote %>% filter(year==2012),aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +
  scale_fill_distiller(name="CA Vote Percent Republican Presidental 2012", palette = "Reds")
CA_Vote2016 <- ggplot(CA_Vote %>% filter(year==2016),aes(geometry=geometry)) + geom_sf(aes(fill = proportion))+
  scale_fill_distiller(name="CA Vote Percent Republican Presidental 2016", palette = "Reds")

# PA vote 
PA_Vote <- vote %>% filter(state == 'Pennsylvania')
PA_Vote2008 <- ggplot(PA_Vote %>% filter(year==2008), aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +scale_fill_distiller(name="PA Vote Percent Republican Presidental 2008", palette = "blues") 
PA_Vote2012 <- ggplot(PA_Vote %>% filter(year==2012),aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +
  scale_fill_distiller(name="PA Vote Percent Republican Presidental 2012", palette = "Blues")
PA_Vote2016 <- ggplot(PA_Vote %>% filter(year==2016),aes(geometry=geometry)) + geom_sf(aes(fill = proportion))+
  scale_fill_distiller(name="PA Vote Percent Republican Presidental 2016", palette = "Blues")

# TX Vote
TX_Vote <- vote %>% filter(state == 'Texas')
TX_Vote2008 <- ggplot(TX_Vote %>% filter(year==2008), aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +scale_fill_distiller(name="TX Vote Percent Republican Presidental 2008", palette = "Reds")
TX_Vote2012 <- ggplot(TX_Vote %>% filter(year==2012),aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +
  scale_fill_distiller(name="TX Vote Percent Republican Presidental 2012", palette = "Reds")
TX_Vote2016 <- ggplot(TX_Vote %>% filter(year==2016),aes(geometry=geometry)) + geom_sf(aes(fill = proportion)) +
  scale_fill_distiller(name="TX Vote Percent Republican Presidental 2016", palette = "Reds")



```



```{r}
unemployment <- read_excel("data/Unemployment.xls", range = cell_limits(c(8, 1))) %>% left_join(county, by = c('FIPStxt' = 'GEOID')) 

# PA
PA <- unemployment %>% filter(substr(FIPStxt,1,2) == '42') 
PA2008 <- ggplot(PA,aes(geometry=geometry)) + geom_sf(aes(fill = Unemployment_rate_2008)) +
  scale_fill_distiller(name="PA Unemployment rate 2008", palette = "Blues") 
PA2012 <- ggplot(PA,aes(geometry=geometry))+ geom_sf(aes(fill = Unemployment_rate_2012))+
  scale_fill_distiller(name="PA Unemployment rate 2012", palette = "Blues")
PA2016 <- ggplot(PA,aes(geometry=geometry)) + geom_sf(aes(fill = Unemployment_rate_2016)) +
  scale_fill_distiller(name="PA Unemployment rate 2016", palette = "Blues")

# CA
CA <- unemployment %>% filter(substr(FIPStxt,1,2) == '06') 
CA2008 <- ggplot(CA,aes(geometry=geometry)) + geom_sf(aes(fill = Unemployment_rate_2008)) +
  scale_fill_distiller(name="CA Unemployment rate 2008", palette = "Blues")
CA2012 <- ggplot(CA,aes(geometry=geometry))+ geom_sf(aes(fill = Unemployment_rate_2012))+
  scale_fill_distiller(name="CA Unemployment rate 2012", palette = "Blues")
CA2016 <- ggplot(CA,aes(geometry=geometry)) + geom_sf(aes(fill = Unemployment_rate_2016)) +
  scale_fill_distiller(name="CA Unemployment rate for 2016", palette = "Blues")

# TX
TX <- unemployment %>% filter(substr(FIPStxt,1,2) == '48') 
TX2008 <- ggplot(TX,aes(geometry=geometry)) + geom_sf(aes(fill = Unemployment_rate_2008)) +
  scale_fill_distiller(name="TX Unemployment rate 2008", palette = "Blues")
TX2012 <- ggplot(TX,aes(geometry=geometry))+ geom_sf(aes(fill = Unemployment_rate_2012))+
  scale_fill_distiller(name="TX Unemployment rate 2012", palette = "Blues")
TX2016 <- ggplot(TX,aes(geometry=geometry)) + geom_sf(aes(fill = Unemployment_rate_2016)) +
  scale_fill_distiller(name="TX Unemployment rate 2016", palette = "Blues")

```

```{r, fig3, fig.height = 15, fig.width = 20}
ggarrange(CA_Vote2008, CA2008,CA_Vote2012, CA2012,CA_Vote2016, CA2016, ncol = 2, nrow=3)
```

```{r fig1, fig.height = 15, fig.width = 20}
ggarrange(TX_Vote2008, TX2008 ,TX_Vote2012, TX2012,TX_Vote2016, TX2016, ncol = 2, nrow=3)
```

```{r fig2, fig.height = 15, fig.width = 20}
ggarrange(PA_Vote2008, PA2008 ,PA_Vote2012, PA2012,PA_Vote2016, PA2016, ncol = 2, nrow=3)
```
